server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    prefix: classpath:static/
    suffix: .html
    cache: false




  datasource:
    url: jdbc:mariadb://localhost:3306/bms_test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 123456
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none